name: Deploy to shinyapps.io

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev
      
      - name: Install rsconnect and shiny
        run: |
          install.packages("rsconnect", repos = "https://cloud.r-project.org/")
          install.packages("shiny", repos = "https://cloud.r-project.org/")
        shell: Rscript {0}
      
      - name: Install app dependencies
        run: |
          # Add any other packages your app uses here
          install.packages(c("ggplot2", "dplyr"), repos = "https://cloud.r-project.org/")
        shell: Rscript {0}
      
      - name: Deploy
        env:
          SHINYAPPS_USERNAME: ${{ vars.SHINYAPPS_USERNAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: Rscript deploy.R
